#!/bin/sh
# Remainder for COSMIC (Pop!_OS) — user-level install. No sudo, nothing outside $HOME. (worksafe tier)
# Implements AUTHORITY.md §2, §3, §5 and PLATFORM.md COSMIC. Re-runnable, and it backs up what it replaces.
#
# Usage: sh install.sh [--fonts|--no-fonts] [--icons|--icons-neutral|--no-icons]
#                      [--art|--black-field|--no-wallpaper] [--all] [--no-ask]
#
# Run it with no arguments on a terminal and it asks three questions -- fonts, icons, background --
# before it writes anything, and takes no answer as the default shown in brackets. Any flag below
# answers its own question in advance and that question is not asked, so a scripted install never
# blocks. With no terminal on stdin (a pipe, a provisioning run) nothing is asked at all and the
# flags and their defaults stand alone.
#
#   --fonts    fetch Montserrat and Hack from their authoritative sources, verify, install per-user
#              (§5). --no-fonts declines. Not asked when both are already on the machine.
#   --icons    repaint this machine's own application icons along the kit's own lightness ramp (§4):
#              every pixel keeps its lightness exactly, and hue and chroma come from that lightness --
#              BLACK -> SELECT -> ACCENT -> LIGHT -> WHITE, neutral at both ends and the home hue
#              through the middle. An icon keeps its shape, its shading and its place among the other
#              icons, in one register. The kit repaints nothing without this flag.
#   --icons-neutral  the same machinery on the four-step neutral ladder, whose chroma is the §2 cast
#              throughout, for a user who wants the dock grey. It is not the safer option and --icons
#              is not a compromise: the point of the kit is a colourful interface that does not
#              interfere, not a colourless one (§0a, §0c). The duotone clears every pole and never
#              reaches CURSOR, whose worth is being the only thing on screen at that hue (§2), so
#              there is nothing here to be safe from. --no-icons declines.
#   --art      background: one public-domain museum photograph, fitted on the BLACK field, with its
#              credit line installed beside it. Photographs are content (§5) and are permitted; this
#              one is not generated by the kit and nothing about it is authored. THIS IS THE DEFAULT,
#              and it has a measured cost -- see section 3b. An unreachable or unverified image is
#              not installed and the background falls back to the flat BLACK field.
#   --black-field   background: the flat BLACK field and nothing else. The desktop §5 declares, and
#              the one that buys the desktop's own labels their margin (§0e).
#   --no-wallpaper  background: leave it alone. Nothing is written and nothing is backed up, so
#              whatever wallpaper is set stays set.
#   --all      --fonts and --icons. It does not cover the background, which has three answers.
#   --no-ask   ask nothing; take the flags and the defaults. Implied when stdin is not a terminal.
#
# --fonts and --icons stay off unless asked for or answered for, and both are the user's call, not
# the kit's: §5 declares the two typefaces but a user may already have them or want others, and §4
# holds that a brand is information until its owner decides otherwise. The background is the one
# question with no off answer -- a desktop shows something -- so it has a default rather than a
# flag, and --no-wallpaper is how you keep your own.
set -e

# Empty means unanswered: §0c asks, or falls back to the default, only for the ones left empty.
WANT_FONTS=''; WANT_ICONS=''; BGCHOICE=''; RAMP=duotone; NOASK=0
for a in "$@"; do
  case "$a" in
    --fonts) WANT_FONTS=1 ;;
    --no-fonts) WANT_FONTS=0 ;;
    --icons) WANT_ICONS=1; RAMP=duotone ;;
    --icons-neutral) WANT_ICONS=1; RAMP=neutral ;;
    --no-icons) WANT_ICONS=0 ;;
    --art)   BGCHOICE=art ;;
    --black-field|--no-art) BGCHOICE=black ;;
    --no-wallpaper) BGCHOICE=none ;;
    --all)   WANT_FONTS=1; WANT_ICONS=1 ;;                  # not the background: three answers, not two
    --no-ask) NOASK=1 ;;
    # The help text is the comment block above, however long it grows: line 2 to the first line that
    # is not a comment, less that line. It has needed its line numbers corrected twice.
    -h|--help) sed -n '2,/^[^#]/p' "$0" | sed '$d; s/^# \{0,1\}//'; exit 0 ;;
    *) echo "remainder: unknown option $a (try --help)" >&2; exit 2 ;;
  esac
done

# --- 0. the account this installs for -------------------------------------------------------------
# Line 2 of this file is a promise, and sudo quietly breaks it. On a default sudoers, sudo sets $HOME
# to /root and every path below is built from $HOME -- so `sudo sh install.sh` themes root: it
# succeeds, it says it succeeded, and it does it to an account nobody is looking at. It also buys
# nothing, because there is no system-wide COSMIC config here that would need root -- which is the
# whole reason line 2 can promise what it promises. Where sudo is configured to keep $HOME instead,
# the same command fills the caller's own config with root-owned files, which is worse. A real root
# shell is neither case and is allowed through: $HOME is /root, root is the account being asked for,
# and that is coherent.
if [ -n "$SUDO_USER" ]; then
  RERUN="sh $0${1:+ $*}"                                    # the command they just typed, minus sudo
  cat >&2 <<MSG
remainder: refusing to run under sudo -- this is a user-level install, and under sudo it is not your
           install. Everything it writes lands under \$HOME (here: $HOME), written as the user sudo
           switched to and not as $SUDO_USER. Nothing the kit writes goes outside \$HOME, so there is
           nothing here that needs root.
           Run it as yourself:  $RERUN
           If you did mean another account: sudo -i (or sudo -i -u NAME), then run it from there.
MSG
  exit 2
fi
if [ "$(id -u)" = 0 ]; then
  echo "remainder: running as root -- installing for root ($HOME), not for any other user."
fi

HERE=$(cd "$(dirname "$0")" && pwd)
KIT=$(cd "$HERE/../.." && pwd)
CFG="${XDG_CONFIG_HOME:-$HOME/.config}/cosmic"
DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/remainder"     # what this script replaced, so it is reversible
PY="${REMAINDER_PYTHON:-python3}"                           # needs Pillow, numpy and cairosvg for --icons

# --- helpers ------------------------------------------------------------------------------------
say() { echo "remainder: $*"; }
fetch() {   # fetch URL OUT
  if   command -v curl >/dev/null 2>&1; then curl -sSL --fail --max-time 120 -o "$2" "$1"
  elif command -v wget >/dev/null 2>&1; then wget -q -O "$2" "$1"
  else say "need curl or wget to fetch fonts" >&2; return 1; fi
}
sha256_of() {
  if   command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum    >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d' ' -f1
  else echo ''; fi
}
verify() {  # verify FILE EXPECTED_SHA256 — an unverified font is not installed
  got=$(sha256_of "$1")
  if [ -z "$got" ]; then say "no sha256sum or shasum on PATH; refusing to install an unverified font" >&2; return 1; fi
  if [ "$got" != "$2" ]; then
    say "checksum mismatch for $(basename "$1")" >&2
    echo "         expected $2" >&2
    echo "         got      $got" >&2
    return 1
  fi
}
backup() {  # backup PATH LABEL — first run only, so a re-run never overwrites the original
  [ -f "$1" ] && [ ! -e "$STATE/$2" ] && cp "$1" "$STATE/$2" && say "saved $1 -> $STATE/$2"
  return 0
}

# --- 0c. the questions ----------------------------------------------------------------------------
# Asked once, up front, before a single file is written: the whole install is consented to before it
# starts rather than one surprise at a time, and Ctrl-C here leaves the machine untouched. A flag
# answers its own question and that question is skipped. With no terminal on stdin nothing is asked,
# which is what a pipe or a provisioning run wants; the defaults are the same on both paths.
ASK=1
[ "$NOASK" = 1 ] && ASK=0
if [ ! -t 0 ] || [ ! -t 1 ]; then ASK=0; fi

yesno() {   # yesno QUESTION DEFAULT(y|n) -- 0 for yes. Empty or EOF takes the default.
  case "$2" in y) _hint='[Y/n]' ;; *) _hint='[y/N]' ;; esac
  printf 'remainder: %s %s ' "$1" "$_hint"
  if ! read -r _reply; then _reply=''; echo; fi
  [ -n "$_reply" ] || _reply=$2
  case "$_reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}
have_font()      { fc-list 2>/dev/null | grep -qi ":$1:\|: $1:"; }
have_icon_deps() { "$PY" -c 'import PIL, numpy, cairosvg' 2>/dev/null; }

# 1. fonts. Asked first because §5 makes them load-bearing: every contrast floor in §0e is a function
# of what 12pt Montserrat renders at, so a machine without them is not running the measured kit.
if [ "$ASK" = 1 ] && [ -z "$WANT_FONTS" ]; then
  if have_font Montserrat && have_font Hack; then
    say "Montserrat and Hack are already installed — not fetching them."
    WANT_FONTS=0
  else
    cat <<'Q'
remainder: §5 declares Montserrat for the UI and Hack for mono, and every contrast floor in §0e is a
           function of what they render at. They are fetched from the two projects themselves at a
           pinned tag, checked against a recorded SHA-256, and installed for this user only.
Q
    if yesno "Download and install them?" y; then WANT_FONTS=1; else WANT_FONTS=0; fi
  fi
fi

# 2. icons. Not offered when the generator cannot run: a question whose answer cannot be honoured is
# worse than the hint that replaces it.
if [ "$ASK" = 1 ] && [ -z "$WANT_ICONS" ]; then
  if have_icon_deps; then
    cat <<'Q'
remainder: the kit can repaint this machine's own application icons in its own ink (§4). Every pixel
           keeps its lightness and takes its hue and chroma from that lightness, so an icon keeps its
           shape and its shading and the dock still reads as itself -- in one register, and nothing on
           it reads as a signal. Nothing is shipped and nothing is downloaded: the art is already
           here. Undone by selecting another icon theme.
Q
    if yesno "Generate the icon theme?" y; then WANT_ICONS=1; else WANT_ICONS=0; fi
  else
    say "icon theme not offered — $PY needs Pillow, numpy and cairosvg (set REMAINDER_PYTHON to a venv python)"
    WANT_ICONS=0
  fi
fi

# 3. background. Three answers, and the cost of the default is stated in the question rather than
# discovered afterwards (§9): a user choosing 1 should know what it does to the desktop's own labels.
if [ "$ASK" = 1 ] && [ -z "$BGCHOICE" ]; then
  cat <<'Q'
remainder: the desktop background.
             1  the museum photograph, fitted on the BLACK field. AIC 1938.454, public domain,
                fetched from the museum and verified, credit installed beside it. Its studio ground
                is light: WHITE desktop labels measure Lc -35.9 at the median over it, against -92.3
                on the bare field, under every floor in §0e. The surround stays BLACK.
             2  the flat BLACK field, and nothing else. The desktop §5 declares -- the tiling gaps
                are then the same value as the rule, dE 0.0, and the labels keep their margin.
             3  leave the background alone. Nothing written, nothing backed up.
Q
  while [ -z "$BGCHOICE" ]; do
    printf 'remainder: choose [1]: '
    if ! read -r _reply; then _reply=''; echo; fi
    case "${_reply:-1}" in
      1) BGCHOICE=art ;;
      2) BGCHOICE=black ;;
      3) BGCHOICE=none ;;
      *) echo "remainder: 1, 2 or 3." >&2 ;;
    esac
  done
fi

# Unanswered means the default: fonts and icons off (§4, §5 -- the user's call, and the palette is
# correct without either), background the photograph.
[ -n "$WANT_FONTS" ] || WANT_FONTS=0
[ -n "$WANT_ICONS" ] || WANT_ICONS=0
[ -n "$BGCHOICE" ]   || BGCHOICE=art

mkdir -p "$CFG" "$STATE"        # the first thing this script writes, and not before here

# --- 1. fonts (§5), asked for or --fonts ----------------------------------------------------------
# UI Montserrat, mono Hack. Fetched from the projects themselves at a pinned tag and checked against a
# recorded SHA-256 — not bundled, and not taken from a redistribution. Measured 2026-09-19; the Hack
# files match the v3.003 release byte for byte.
FONTS="$DATA/fonts/remainder"
HACK_TAG=v3.003
HACK_URL="https://github.com/source-foundry/Hack/releases/download/$HACK_TAG/Hack-$HACK_TAG-ttf.tar.xz"
HACK_SHA=d9ed5d0a07525c7e7bd587b4364e4bc41021dd668658d09864453d9bb374a78d
HACK_LICENSE_URL="https://raw.githubusercontent.com/source-foundry/Hack/$HACK_TAG/LICENSE.md"
HACK_LICENSE_SHA=1f61bb7c790c59b4b0ecdf304628b94e42ae4c8020094a8c3da73381ab212623
MONT_TAG=v7.222
MONT_RAW="https://raw.githubusercontent.com/JulietaUla/Montserrat/$MONT_TAG"
# file:sha256 — the four faces §5 asks for, plus the licence the OFL requires to travel with them
MONT_FILES="fonts/ttf/Montserrat-Regular.ttf:6eabd0fb8e3066b6155bac338ef5a6c35b9963ab3f39be7c67edc4a99d870699
fonts/ttf/Montserrat-Bold.ttf:4e6d93bc38122c371acb8dc0dbefbf2649c235191e1be136bb5720546d719808
fonts/ttf/Montserrat-Italic.ttf:928e6fc816a1502dc21514f38ae5f9e6d59ca6a857fa96eeb1e63756aa3e6233
fonts/ttf/Montserrat-BoldItalic.ttf:9a2f1e3179e3a9254cb09c0cb2f7fccab0ad00863ddcb5cb5abf89c036125dda
OFL.txt:41f82bb4d24b304f30f7136bc47abdd083782e4265c984160f5649d1e78ea49c"

install_fonts() {
  TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
  mkdir -p "$FONTS/hack" "$FONTS/montserrat"

  say "fetching Hack $HACK_TAG from source-foundry/Hack"
  fetch "$HACK_URL" "$TMP/hack.tar.xz" || return 1
  verify "$TMP/hack.tar.xz" "$HACK_SHA" || return 1
  tar xJf "$TMP/hack.tar.xz" -C "$TMP"
  for f in Hack-Regular Hack-Bold Hack-Italic Hack-BoldItalic; do
    [ -f "$TMP/$f.ttf" ] || { say "Hack tarball is missing $f.ttf" >&2; return 1; }
    cp "$TMP/$f.ttf" "$FONTS/hack/"
  done
  fetch "$HACK_LICENSE_URL" "$TMP/Hack-LICENSE.md" || return 1
  verify "$TMP/Hack-LICENSE.md" "$HACK_LICENSE_SHA" || return 1
  cp "$TMP/Hack-LICENSE.md" "$FONTS/hack/LICENSE.md"

  say "fetching Montserrat $MONT_TAG from JulietaUla/Montserrat"
  echo "$MONT_FILES" | while IFS=: read -r path sha; do
    [ -n "$path" ] || continue
    base=$(basename "$path")
    fetch "$MONT_RAW/$path" "$TMP/$base" || exit 1
    verify "$TMP/$base" "$sha" || exit 1
    cp "$TMP/$base" "$FONTS/montserrat/$base"
  done || return 1

  command -v fc-cache >/dev/null 2>&1 && fc-cache -f "$FONTS" >/dev/null 2>&1 || true
  say "fonts installed in $FONTS (Hack $HACK_TAG, MIT; Montserrat $MONT_TAG, SIL OFL 1.1)"
}

if [ "$WANT_FONTS" = 1 ]; then
  install_fonts || { say "fonts NOT installed — nothing unverified was written"; FONTS_FAILED=1; }
elif [ "$ASK" = 0 ]; then
  # Only worth saying to someone who was not asked: §0e's floors are a function of these faces, so a
  # machine without them is not running the measured kit. Someone who just declined the question
  # knows that already and does not need the flag read back to them.
  for f in Montserrat Hack; do
    have_font "$f" || say "font '$f' not installed — run: sh install.sh --fonts"
  done
fi

# --- 2. light mode (§2). The palette is WHITE fields and BLACK text; no dark builder is shipped. --
mkdir -p "$CFG/com.system76.CosmicTheme.Mode/v1"
printf 'false' > "$CFG/com.system76.CosmicTheme.Mode/v1/is_dark"
printf 'false' > "$CFG/com.system76.CosmicTheme.Mode/v1/auto_switch"

# --- 3. background (§5): no painting, so a flat BLACK field. The gaps ARE the rule: the rule is -----
# BLACK, so a gap between two windows is the same value as the line the kit draws (dE 0.0).
# A file rather than a Color source: cosmic-greeter draws the lock screen from this same key with its
# own image loader and does not take a Color. A solid PNG needs no Pillow.
# The field is written whenever the background is written at all, and it is never unused: 3b fits the
# photograph ON it, so the surround is this value and the gaps still read as the rule; --black-field
# makes it the whole desktop; and a failed or unverified fetch falls back to it. --no-wallpaper skips
# all of it -- if the user is keeping their own background, the kit has no business writing a file
# for one, nor a backup of a key it is not going to touch.
PICS="$DATA/remainder"
BGPNG="$PICS/black_field.png"
if [ "$BGCHOICE" = none ]; then
  say "background left alone — nothing written, nothing backed up"
else
mkdir -p "$PICS"
python3 - "$BGPNG" <<'PY'
import struct, sys, zlib
out, w, h = sys.argv[1], 16, 16                     # BLACK #10080C (§2, §5). Zoom fills any output.
def chunk(t, d): return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
row = b'\x00' + bytes([0x10, 0x08, 0x0C]) * w
png = (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0))
       + chunk(b'IDAT', zlib.compress(row * h, 9)) + chunk(b'IEND', b''))
open(out, 'wb').write(png)
PY
fi
# --- 3b. the painting (§5, §0a), the default background; --black-field declines it -----------------------------------------------------------
# §5 says it plainly: "Photographs are content (§0a) and are permitted; nothing the kit generates is
# in color." So this is not an exception to §1 and is not measured against it. It is content, and the
# pole test does not apply to content (§3) -- which is the only reason a wallpaper may carry hue at all.
#
# WHY THIS OBJECT. Fahua ware separates its glazes with raised slip trails so the colors cannot run
# together: color kept apart by a drawn rule, which is §5's geometry argument fired in a kiln in the
# 16th century. Measured 2026-09-19 over 635,400 sampled pixels, its two glazes land in the kit's two
# unclaimed arcs and nowhere else:
#   aubergine  #532C48  L 0.355  C 0.069  h 338.9   home arc; BELOW C_FLOOR 0.092, so by the kit's own
#                                                   test it carries no readable hue -- dE 5.7 to SELECT,
#                                                   6.2 to DARK. It is the cast register, not chrome.
#   teal       #00A3B7  L 0.655  C 0.113  h 210.3   cursor gap; clear, 38.8deg from success, needs 12.0.
#                                                   dE 12.9 to CURSOR. 91.3% of the readable color here.
# Nothing above is authored and none of it lands in a surface file. It is recorded because §9 says a
# value arrives with its measurement, and because it is why this photograph and not another.
#
# THE COST, MEASURED, AND IT IS REAL. The object is shot on a light studio ground that is 71.1% of the
# frame at L 0.74-0.80. §5 argues the desktop should be a flat BLACK field, partly so the tiling gaps
# ARE the rule (dE 0.0) and partly for the desktop's own labels: WHITE on BLACK is Lc -92.3. Over this
# photograph WHITE measures Lc -87.0 on its darkest 5% but only -35.9 at its median and -24.4 on its
# lightest 5% -- under every floor in §0e. Fit, not Zoom, is chosen for exactly this reason: it keeps
# the surround BLACK so the gaps still read as the rule, and it presents the object as an object
# rather than cropping a museum photograph to fit a screen. The middle of the screen is still light.
# That is the trade the default makes, and it is the whole of what answer 2 (--black-field) buys
# back. The installer states it in the question and again in the summary, because a floor the kit
# knowingly ships under is not something to find out about later (§9).
ART_ID=d877f771-ebb8-bfef-6af0-7b18584ab4d0
ART_W=2868                       # the IIIF maxArea for this image is 6453000 px; 2868x2250 is native
ART_URL="https://www.artic.edu/iiif/2/$ART_ID/full/$ART_W,/0/default.jpg"
ART_SHA=a8dc3f9eeb91f5e021ddab9fb94e7a35d20664212f591bf51e4e42a92da076a1
ART_PAGE="https://www.artic.edu/artworks/88202/jar-with-peonies-and-lid"
ART_FILE="$PICS/aic-1938.454-jar-with-peonies.jpg"

install_art() {   # fetch from the museum, verify, and install the credit line beside the file (§12)
  TMPA=$(mktemp -d) || return 1
  say "fetching AIC 1938.454 from artic.edu ($ART_W px)"
  fetch "$ART_URL" "$TMPA/art.jpg" || { rm -rf "$TMPA"; return 1; }
  verify "$TMPA/art.jpg" "$ART_SHA" || { rm -rf "$TMPA"; return 1; }
  cp "$TMPA/art.jpg" "$ART_FILE"; rm -rf "$TMPA"
  # The credit travels with the file, the way §12 makes a font licence travel with the faces.
  cat > "$PICS/CREDIT-aic-1938.454.txt" <<CREDIT
Jar with Peonies and lid
China, Ming dynasty (1368-1644), 16th century
Fahua ware; stoneware with underglaze molded decoration and blue, purple,
and white glazes, wood
16.1 x 17.5 cm (6 5/16 x 6 7/8 in.); Diam.: 17.5 cm (6 7/8 in.)

Credit line   Bequest of Kate S. Buckingham
Reference     1938.454
Department    Arts of Asia
Collection    The Art Institute of Chicago
Object page   $ART_PAGE

Rights        The Art Institute of Chicago publishes this work as public domain
              under its Open Access policy (the API reports is_public_domain:
              true and carries no copyright notice). Collection metadata is
              released CC0 1.0. Use is subject to the museum's terms:
              https://www.artic.edu/terms
              https://creativecommons.org/publicdomain/zero/1.0/

Fetched       $ART_URL
              sha256 $ART_SHA
              verified by worksafe/cosmic/install.sh on first install

Installed by the Remainder theme kit. The kit neither owns nor relicenses this
image: it is fetched from the museum, unmodified, and is content (AUTHORITY.md
section 5), not part of the palette. Delete this file and the image to remove it.
CREDIT
  say "credit installed -> $PICS/CREDIT-aic-1938.454.txt"
}

# Fit's fill colour is written here and not chosen in Settings on purpose: cosmic-settings builds
# ScalingMode::Fit([0.0, 0.0, 0.0]) for every "Fit" the GUI offers (wallpaper/mod.rs), and #000000 is
# reserved by §3. Writing the entry is the only way the surround is the kit's BLACK and not the
# reserved value. cosmic-bg fills with the triple as given (scaler.rs fit(), no gamma step), so these
# are sRGB/255 -- the same notation the panel config already uses (CONTRIBUTING.md §8).
BGSRC="$BGPNG"
BGMODE="Zoom"
if [ "$BGCHOICE" = art ]; then
  if install_art; then
    BGSRC="$ART_FILE"
    BGMODE="Fit((0.062745, 0.031373, 0.047059))"   # BLACK #10080C: 16/255, 8/255, 12/255
  else
    say "artwork NOT installed -- nothing unverified was written; keeping the flat BLACK field"
    ART_FAILED=1
  fi
fi

if [ "$BGCHOICE" != none ]; then
BG="$CFG/com.system76.CosmicBackground/v1"; mkdir -p "$BG"
backup "$BG/all" "cosmic-background-all.ron"
cat > "$BG/all" <<RON
(
    output: "all",
    source: Path("$BGSRC"),
    filter_by_theme: true,
    rotation_frequency: 300,
    filter_method: Lanczos,
    scaling_mode: $BGMODE,
    sampling_method: Alphanumeric,
)
RON
printf 'true' > "$BG/same-on-all"
fi

# --- 4. toolkit and panel: Montserrat UI, Hack mono, compact; panel LIGHT (§2) --------------------
# The panel takes a flat Color because COSMIC would otherwise paint it with the window background.
for d in com.system76.CosmicTk com.system76.CosmicPanel.Panel com.system76.CosmicPanel.Dock; do
  [ -d "$HERE/cosmic-config/$d/v1" ] || continue
  mkdir -p "$CFG/$d/v1"
  for f in "$HERE/cosmic-config/$d/v1/"*; do
    backup "$CFG/$d/v1/$(basename "$f")" "$d.$(basename "$f")"
    cp "$f" "$CFG/$d/v1/"
  done
done

# --- 5. theme (§2, §3, §5): the gaps in remainder.ron ARE the rule width; change it there ---------
# cosmic-settings prints two ERRORs on stderr -- "1:1: Expected identifier" and "failed to get key
# 'frosted_maximized_apps'" -- on every export AND every import, and exits 0 either way. They are about
# its own config state, not about remainder.ron: an export, which never reads that file, prints the same
# two. Not suppressed, because hiding them would hide a real failure with them.
if command -v cosmic-settings >/dev/null 2>&1; then
  if [ ! -e "$STATE/appearance.before-remainder.ron" ]; then
    cosmic-settings appearance export "$STATE/appearance.before-remainder.ron" >/dev/null || true
    if [ -s "$STATE/appearance.before-remainder.ron" ]; then
      say "saved the current appearance -> $STATE/appearance.before-remainder.ron"
    else
      say "WARNING: could not export the current appearance. The theme import below will NOT be"
      say "         undoable from $STATE. Ctrl-C now if that matters."
    fi
  fi
  cosmic-settings appearance import "$HERE/remainder.ron"
else
  say "cosmic-settings not on PATH — import $HERE/remainder.ron from Settings > Desktop > Appearance > Import"
fi

# --- 6. terminal: add the scheme to COSMIC Terminal's light schemes and select it -----------------
# Discovery carried over from the parent kit unchanged; the scheme itself is this kit's (§0a content).
TERM_CFG="$CFG/com.system76.CosmicTerm/v1"; mkdir -p "$TERM_CFG"
backup "$TERM_CFG/color_schemes_light" "cosmic-term-color_schemes_light.ron"
python3 - "$HERE/remainder-term.ron" "$TERM_CFG" <<'PY'
import os, re, sys
src, cfg = sys.argv[1], sys.argv[2]
scheme = re.sub(r'^\s*//.*\n', '', open(src).read(), flags=re.M).strip()
name = re.search(r'name:\s*"([^"]+)"', scheme).group(1)
path = os.path.join(cfg, 'color_schemes_light')
cur = open(path).read() if os.path.exists(path) else '{\n}'
if f'name: "{name}"' not in cur:
    entries = re.findall(r'^\s*(\d+):', cur, flags=re.M)
    nxt = max(map(int, entries)) + 1 if entries else 0
    body = cur.rstrip().rstrip('}').rstrip()
    new = body + f'\n    {nxt}: {scheme},\n}}' if body.endswith('{') else body.rstrip(',') + f',\n    {nxt}: {scheme},\n}}'
    open(path, 'w').write(new)
open(os.path.join(cfg, 'syntax_theme_light'), 'w').write(f'"{name}"')
print(f'remainder: terminal scheme "{name}" installed and selected')
PY

# --- 7. icons (§4), asked for or --icons -----------------------------------------------------------------------
# The user's own installed icons, repainted along the ramp through the values §2 authors and written as
# an overlay theme. Nothing is shipped and nothing is redistributed: the art is already on this machine.
# Reverse it by selecting another icon theme.
ICONS="$DATA/icons/remainder"
if [ "$WANT_ICONS" = 1 ]; then
  if "$PY" -c 'import PIL, numpy, cairosvg' 2>/dev/null; then
    INHERITS="Cosmic,Pop,Adwaita,hicolor"
    rm -rf "$ICONS"
    "$PY" "$KIT/build/icon_theme.py" --out "$ICONS" --inherits "$INHERITS" --ramp "$RAMP" | head -1
    command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q -t "$ICONS" || true
    backup "$CFG/com.system76.CosmicTk/v1/icon_theme" "cosmic-tk-icon_theme.ron"
    printf '"remainder"' > "$CFG/com.system76.CosmicTk/v1/icon_theme"
    pgrep -x cosmic-panel >/dev/null 2>&1 && pkill -x cosmic-panel || true   # it reads the icon theme at startup
  else
    say "icons NOT generated — $PY needs Pillow, numpy and cairosvg (set REMAINDER_PYTHON to a venv python)"
    ICONS=''
  fi
else
  ICONS=''
fi

# --- 8. what happened ----------------------------------------------------------------------------
[ "$WANT_FONTS" = 1 ] && [ -z "$FONTS_FAILED" ] && F="fonts ($FONTS)" || F="fonts left alone"
[ -n "$ICONS" ] && [ -d "$ICONS" ] && I="icons ($ICONS)" || I="icons left alone (§4 default)"
case "$BGCHOICE" in
  art)   if [ -z "$ART_FAILED" ]; then
           B="background: AIC 1938.454 fitted on BLACK (credit in $PICS/CREDIT-aic-1938.454.txt)"
         else
           B="background: flat BLACK field (the photograph could not be fetched or verified)"
         fi ;;
  black) B="background: flat BLACK field (§5)" ;;
  none)  B="background: left alone" ;;
esac
cat <<MSG
remainder: light mode, theme, toolkit config, terminal scheme; $B; $F; $I.
           what was replaced is in $STATE
Log out/in if the panel, background or terminal does not refresh.
MSG
if [ "$BGCHOICE" = art ] && [ -z "$ART_FAILED" ]; then cat <<'MSG'
           note: the photograph is shot on a light ground (71.1% of the frame at L 0.74-0.80).
           WHITE over it measures Lc -35.9 at its median against -92.3 on the BLACK field, so the
           desktop's own labels lose the margin §5 buys them. The surround stays BLACK; the middle
           does not. Re-run with --black-field to go back.
MSG
fi
