#!/bin/sh
# Remainder for COSMIC (Pop!_OS) — user-level install. No sudo, nothing outside $HOME. (worksafe tier)
# Implements AUTHORITY.md §2, §3, §5 and PLATFORM.md COSMIC. Re-runnable, and it backs up what it replaces.
#
# Usage: sh install.sh [--fonts] [--icons|--icons-neutral] [--art] [--all]
#   (default)  light mode, the theme, the toolkit config, the terminal scheme, a flat BLACK background
#   --fonts    fetch Montserrat and Hack from their authoritative sources, verify, install per-user (§5)
#   --icons    project this machine's own application icons onto all seven values the kit authors --
#              the ladder plus ACCENT, SELECT and CURSOR (§4). Opt-in; the kit repaints nothing
#              without it.
#   --icons-neutral  the same, on the four-step neutral ladder alone, for a user who wants the dock
#              grey. It is not the safer option and --icons is not a compromise: the point of the kit
#              is a colourful interface that does not interfere, not a colourless one (§0a, §0c), and
#              icons projected onto all seven values are the intended result.
#   --art      fetch one public-domain museum photograph and set it as the background, fitted on the
#              BLACK field, with its credit line installed beside it. Photographs are content (§5) and
#              are permitted; this one is not generated by the kit and nothing about it is authored.
#              It has a measured cost -- see section 3b. Off by default.
#   --all      --fonts, --icons and --art
#
# Every option is off by default and every one is the user's call, not the kit's: §5 declares the two
# typefaces but a user may already have them or want others, §4 holds that a brand is information
# until its owner decides otherwise, and a wallpaper is the most personal surface on the machine.
set -e

WANT_FONTS=0; WANT_ICONS=0; WANT_ART=0; ANCHORS=all
for a in "$@"; do
  case "$a" in
    --fonts) WANT_FONTS=1 ;;
    --icons) WANT_ICONS=1 ;;
    --icons-neutral) WANT_ICONS=1; ANCHORS=neutral ;;
    --art)   WANT_ART=1 ;;
    --all)   WANT_FONTS=1; WANT_ICONS=1; WANT_ART=1 ;;
    -h|--help) sed -n '2,23p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "remainder: unknown option $a (try --help)" >&2; exit 2 ;;
  esac
done

HERE=$(cd "$(dirname "$0")" && pwd)
KIT=$(cd "$HERE/../.." && pwd)
CFG="${XDG_CONFIG_HOME:-$HOME/.config}/cosmic"
DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/remainder"     # what this script replaced, so it is reversible
PY="${REMAINDER_PYTHON:-python3}"                           # needs Pillow, numpy and cairosvg for --icons
mkdir -p "$CFG" "$STATE"

# --- helpers ------------------------------------------------------------------------------------
say() { echo "remainder: $*"; }
fetch() {   # fetch URL OUT
  if   command -v curl >/dev/null 2>&1; then curl -sSL --fail --max-time 120 -o "$2" "$1"
  elif command -v wget >/dev/null 2>&1; then wget -q -O "$2" "$1"
  else say "need curl or wget to fetch fonts" >&2; return 1; fi
}
sha256_of() {
  if   command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum    >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d' ' -f1
  else echo ''; fi
}
verify() {  # verify FILE EXPECTED_SHA256 — an unverified font is not installed
  got=$(sha256_of "$1")
  if [ -z "$got" ]; then say "no sha256sum or shasum on PATH; refusing to install an unverified font" >&2; return 1; fi
  if [ "$got" != "$2" ]; then
    say "checksum mismatch for $(basename "$1")" >&2
    echo "         expected $2" >&2
    echo "         got      $got" >&2
    return 1
  fi
}
backup() {  # backup PATH LABEL — first run only, so a re-run never overwrites the original
  [ -f "$1" ] && [ ! -e "$STATE/$2" ] && cp "$1" "$STATE/$2" && say "saved $1 -> $STATE/$2"
  return 0
}

# --- 1. fonts (§5), opt-in ----------------------------------------------------------------------
# UI Montserrat, mono Hack. Fetched from the projects themselves at a pinned tag and checked against a
# recorded SHA-256 — not bundled, and not taken from a redistribution. Measured 2026-09-19; the Hack
# files match the v3.003 release byte for byte.
FONTS="$DATA/fonts/remainder"
HACK_TAG=v3.003
HACK_URL="https://github.com/source-foundry/Hack/releases/download/$HACK_TAG/Hack-$HACK_TAG-ttf.tar.xz"
HACK_SHA=d9ed5d0a07525c7e7bd587b4364e4bc41021dd668658d09864453d9bb374a78d
HACK_LICENSE_URL="https://raw.githubusercontent.com/source-foundry/Hack/$HACK_TAG/LICENSE.md"
HACK_LICENSE_SHA=1f61bb7c790c59b4b0ecdf304628b94e42ae4c8020094a8c3da73381ab212623
MONT_TAG=v7.222
MONT_RAW="https://raw.githubusercontent.com/JulietaUla/Montserrat/$MONT_TAG"
# file:sha256 — the four faces §5 asks for, plus the licence the OFL requires to travel with them
MONT_FILES="fonts/ttf/Montserrat-Regular.ttf:6eabd0fb8e3066b6155bac338ef5a6c35b9963ab3f39be7c67edc4a99d870699
fonts/ttf/Montserrat-Bold.ttf:4e6d93bc38122c371acb8dc0dbefbf2649c235191e1be136bb5720546d719808
fonts/ttf/Montserrat-Italic.ttf:928e6fc816a1502dc21514f38ae5f9e6d59ca6a857fa96eeb1e63756aa3e6233
fonts/ttf/Montserrat-BoldItalic.ttf:9a2f1e3179e3a9254cb09c0cb2f7fccab0ad00863ddcb5cb5abf89c036125dda
OFL.txt:41f82bb4d24b304f30f7136bc47abdd083782e4265c984160f5649d1e78ea49c"

install_fonts() {
  TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
  mkdir -p "$FONTS/hack" "$FONTS/montserrat"

  say "fetching Hack $HACK_TAG from source-foundry/Hack"
  fetch "$HACK_URL" "$TMP/hack.tar.xz" || return 1
  verify "$TMP/hack.tar.xz" "$HACK_SHA" || return 1
  tar xJf "$TMP/hack.tar.xz" -C "$TMP"
  for f in Hack-Regular Hack-Bold Hack-Italic Hack-BoldItalic; do
    [ -f "$TMP/$f.ttf" ] || { say "Hack tarball is missing $f.ttf" >&2; return 1; }
    cp "$TMP/$f.ttf" "$FONTS/hack/"
  done
  fetch "$HACK_LICENSE_URL" "$TMP/Hack-LICENSE.md" || return 1
  verify "$TMP/Hack-LICENSE.md" "$HACK_LICENSE_SHA" || return 1
  cp "$TMP/Hack-LICENSE.md" "$FONTS/hack/LICENSE.md"

  say "fetching Montserrat $MONT_TAG from JulietaUla/Montserrat"
  echo "$MONT_FILES" | while IFS=: read -r path sha; do
    [ -n "$path" ] || continue
    base=$(basename "$path")
    fetch "$MONT_RAW/$path" "$TMP/$base" || exit 1
    verify "$TMP/$base" "$sha" || exit 1
    cp "$TMP/$base" "$FONTS/montserrat/$base"
  done || return 1

  command -v fc-cache >/dev/null 2>&1 && fc-cache -f "$FONTS" >/dev/null 2>&1 || true
  say "fonts installed in $FONTS (Hack $HACK_TAG, MIT; Montserrat $MONT_TAG, SIL OFL 1.1)"
}

if [ "$WANT_FONTS" = 1 ]; then
  install_fonts || { say "fonts NOT installed — nothing unverified was written"; FONTS_FAILED=1; }
else
  for f in Montserrat Hack; do
    fc-list 2>/dev/null | grep -qi ":$f:\|: $f:" || say "font '$f' not installed — run: sh install.sh --fonts"
  done
fi

# --- 2. light mode (§2). The palette is WHITE fields and BLACK text; no dark builder is shipped. --
mkdir -p "$CFG/com.system76.CosmicTheme.Mode/v1"
printf 'false' > "$CFG/com.system76.CosmicTheme.Mode/v1/is_dark"
printf 'false' > "$CFG/com.system76.CosmicTheme.Mode/v1/auto_switch"

# --- 3. background (§5): no painting, so a flat BLACK field. The gaps ARE the rule: the rule is -----
# BLACK, so a gap between two windows is the same value as the line the kit draws (dE 0.0).
# A file rather than a Color source: cosmic-greeter draws the lock screen from this same key with its
# own image loader and does not take a Color. A solid PNG needs no Pillow.
# This is still the default and still what §5 argues for. --art (3b) replaces the source and the
# scaling mode below, and keeps this file, because a failed or unverified fetch falls back to it.
PICS="$DATA/remainder"; mkdir -p "$PICS"
BGPNG="$PICS/black_field.png"
python3 - "$BGPNG" <<'PY'
import struct, sys, zlib
out, w, h = sys.argv[1], 16, 16                     # BLACK #10080C (§2, §5). Zoom fills any output.
def chunk(t, d): return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
row = b'\x00' + bytes([0x10, 0x08, 0x0C]) * w
png = (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0))
       + chunk(b'IDAT', zlib.compress(row * h, 9)) + chunk(b'IEND', b''))
open(out, 'wb').write(png)
PY
# --- 3b. the painting (§5, §0a), opt-in -----------------------------------------------------------
# §5 says it plainly: "Photographs are content (§0a) and are permitted; nothing the kit generates is
# in color." So this is not an exception to §1 and is not measured against it. It is content, and the
# pole test does not apply to content (§3) -- which is the only reason a wallpaper may carry hue at all.
#
# WHY THIS OBJECT. Fahua ware separates its glazes with raised slip trails so the colors cannot run
# together: color kept apart by a drawn rule, which is §5's geometry argument fired in a kiln in the
# 16th century. Measured 2026-09-19 over 635,400 sampled pixels, its two glazes land in the kit's two
# unclaimed arcs and nowhere else:
#   aubergine  #532C48  L 0.355  C 0.069  h 338.9   home arc; BELOW C_FLOOR 0.092, so by the kit's own
#                                                   test it carries no readable hue -- dE 5.7 to SELECT,
#                                                   6.2 to DARK. It is the cast register, not chrome.
#   teal       #00A3B7  L 0.655  C 0.113  h 210.3   cursor gap; clear, 38.8deg from success, needs 12.0.
#                                                   dE 12.9 to CURSOR. 91.3% of the readable color here.
# Nothing above is authored and none of it lands in a surface file. It is recorded because §9 says a
# value arrives with its measurement, and because it is why this photograph and not another.
#
# THE COST, MEASURED, AND IT IS REAL. The object is shot on a light studio ground that is 71.1% of the
# frame at L 0.74-0.80. §5 argues the desktop should be a flat BLACK field, partly so the tiling gaps
# ARE the rule (dE 0.0) and partly for the desktop's own labels: WHITE on BLACK is Lc -92.3. Over this
# photograph WHITE measures Lc -87.0 on its darkest 5% but only -35.9 at its median and -24.4 on its
# lightest 5% -- under every floor in §0e. Fit, not Zoom, is chosen for exactly this reason: it keeps
# the surround BLACK so the gaps still read as the rule, and it presents the object as an object
# rather than cropping a museum photograph to fit a screen. The middle of the screen is still light.
# That is the trade --art makes, and a user who wants the §5 desktop should not pass it.
ART_ID=d877f771-ebb8-bfef-6af0-7b18584ab4d0
ART_W=2868                       # the IIIF maxArea for this image is 6453000 px; 2868x2250 is native
ART_URL="https://www.artic.edu/iiif/2/$ART_ID/full/$ART_W,/0/default.jpg"
ART_SHA=a8dc3f9eeb91f5e021ddab9fb94e7a35d20664212f591bf51e4e42a92da076a1
ART_PAGE="https://www.artic.edu/artworks/88202/jar-with-peonies-and-lid"
ART_FILE="$PICS/aic-1938.454-jar-with-peonies.jpg"

install_art() {   # fetch from the museum, verify, and install the credit line beside the file (§12)
  TMPA=$(mktemp -d) || return 1
  say "fetching AIC 1938.454 from artic.edu ($ART_W px)"
  fetch "$ART_URL" "$TMPA/art.jpg" || { rm -rf "$TMPA"; return 1; }
  verify "$TMPA/art.jpg" "$ART_SHA" || { rm -rf "$TMPA"; return 1; }
  cp "$TMPA/art.jpg" "$ART_FILE"; rm -rf "$TMPA"
  # The credit travels with the file, the way §12 makes a font licence travel with the faces.
  cat > "$PICS/CREDIT-aic-1938.454.txt" <<CREDIT
Jar with Peonies and lid
China, Ming dynasty (1368-1644), 16th century
Fahua ware; stoneware with underglaze molded decoration and blue, purple,
and white glazes, wood
16.1 x 17.5 cm (6 5/16 x 6 7/8 in.); Diam.: 17.5 cm (6 7/8 in.)

Credit line   Bequest of Kate S. Buckingham
Reference     1938.454
Department    Arts of Asia
Collection    The Art Institute of Chicago
Object page   $ART_PAGE

Rights        The Art Institute of Chicago publishes this work as public domain
              under its Open Access policy (the API reports is_public_domain:
              true and carries no copyright notice). Collection metadata is
              released CC0 1.0. Use is subject to the museum's terms:
              https://www.artic.edu/terms
              https://creativecommons.org/publicdomain/zero/1.0/

Fetched       $ART_URL
              sha256 $ART_SHA
              verified by worksafe/cosmic/install.sh on first install

Installed by the Remainder theme kit. The kit neither owns nor relicenses this
image: it is fetched from the museum, unmodified, and is content (AUTHORITY.md
section 5), not part of the palette. Delete this file and the image to remove it.
CREDIT
  say "credit installed -> $PICS/CREDIT-aic-1938.454.txt"
}

# Fit's fill colour is written here and not chosen in Settings on purpose: cosmic-settings builds
# ScalingMode::Fit([0.0, 0.0, 0.0]) for every "Fit" the GUI offers (wallpaper/mod.rs), and #000000 is
# reserved by §3. Writing the entry is the only way the surround is the kit's BLACK and not the
# reserved value. cosmic-bg fills with the triple as given (scaler.rs fit(), no gamma step), so these
# are sRGB/255 -- the same notation the panel config already uses (CONTRIBUTING.md §8).
BGSRC="$BGPNG"
BGMODE="Zoom"
if [ "$WANT_ART" = 1 ]; then
  if install_art; then
    BGSRC="$ART_FILE"
    BGMODE="Fit((0.062745, 0.031373, 0.047059))"   # BLACK #10080C: 16/255, 8/255, 12/255
  else
    say "artwork NOT installed -- nothing unverified was written; keeping the flat BLACK field"
    ART_FAILED=1
  fi
fi

BG="$CFG/com.system76.CosmicBackground/v1"; mkdir -p "$BG"
backup "$BG/all" "cosmic-background-all.ron"
cat > "$BG/all" <<RON
(
    output: "all",
    source: Path("$BGSRC"),
    filter_by_theme: true,
    rotation_frequency: 300,
    filter_method: Lanczos,
    scaling_mode: $BGMODE,
    sampling_method: Alphanumeric,
)
RON
printf 'true' > "$BG/same-on-all"

# --- 4. toolkit and panel: Montserrat UI, Hack mono, compact; panel LIGHT (§2) --------------------
# The panel takes a flat Color because COSMIC would otherwise paint it with the window background.
for d in com.system76.CosmicTk com.system76.CosmicPanel.Panel com.system76.CosmicPanel.Dock; do
  [ -d "$HERE/cosmic-config/$d/v1" ] || continue
  mkdir -p "$CFG/$d/v1"
  for f in "$HERE/cosmic-config/$d/v1/"*; do
    backup "$CFG/$d/v1/$(basename "$f")" "$d.$(basename "$f")"
    cp "$f" "$CFG/$d/v1/"
  done
done

# --- 5. theme (§2, §3, §5): the gaps in remainder.ron ARE the rule width; change it there ---------
# cosmic-settings prints two ERRORs on stderr -- "1:1: Expected identifier" and "failed to get key
# 'frosted_maximized_apps'" -- on every export AND every import, and exits 0 either way. They are about
# its own config state, not about remainder.ron: an export, which never reads that file, prints the same
# two. Not suppressed, because hiding them would hide a real failure with them.
if command -v cosmic-settings >/dev/null 2>&1; then
  if [ ! -e "$STATE/appearance.before-remainder.ron" ]; then
    cosmic-settings appearance export "$STATE/appearance.before-remainder.ron" >/dev/null || true
    if [ -s "$STATE/appearance.before-remainder.ron" ]; then
      say "saved the current appearance -> $STATE/appearance.before-remainder.ron"
    else
      say "WARNING: could not export the current appearance. The theme import below will NOT be"
      say "         undoable from $STATE. Ctrl-C now if that matters."
    fi
  fi
  cosmic-settings appearance import "$HERE/remainder.ron"
else
  say "cosmic-settings not on PATH — import $HERE/remainder.ron from Settings > Desktop > Appearance > Import"
fi

# --- 6. terminal: add the scheme to COSMIC Terminal's light schemes and select it -----------------
# Discovery carried over from the parent kit unchanged; the scheme itself is this kit's (§0a content).
TERM_CFG="$CFG/com.system76.CosmicTerm/v1"; mkdir -p "$TERM_CFG"
backup "$TERM_CFG/color_schemes_light" "cosmic-term-color_schemes_light.ron"
python3 - "$HERE/remainder-term.ron" "$TERM_CFG" <<'PY'
import os, re, sys
src, cfg = sys.argv[1], sys.argv[2]
scheme = re.sub(r'^\s*//.*\n', '', open(src).read(), flags=re.M).strip()
name = re.search(r'name:\s*"([^"]+)"', scheme).group(1)
path = os.path.join(cfg, 'color_schemes_light')
cur = open(path).read() if os.path.exists(path) else '{\n}'
if f'name: "{name}"' not in cur:
    entries = re.findall(r'^\s*(\d+):', cur, flags=re.M)
    nxt = max(map(int, entries)) + 1 if entries else 0
    body = cur.rstrip().rstrip('}').rstrip()
    new = body + f'\n    {nxt}: {scheme},\n}}' if body.endswith('{') else body.rstrip(',') + f',\n    {nxt}: {scheme},\n}}'
    open(path, 'w').write(new)
open(os.path.join(cfg, 'syntax_theme_light'), 'w').write(f'"{name}"')
print(f'remainder: terminal scheme "{name}" installed and selected')
PY

# --- 7. icons (§4), opt-in -----------------------------------------------------------------------
# The user's own installed icons, projected onto the seven values §2 authors and written as an overlay
# theme. Nothing is shipped and nothing is redistributed: the art is already on this machine. Reverse
# it by selecting another icon theme.
ICONS="$DATA/icons/remainder"
if [ "$WANT_ICONS" = 1 ]; then
  if "$PY" -c 'import PIL, numpy, cairosvg' 2>/dev/null; then
    INHERITS="Cosmic,Pop,Adwaita,hicolor"
    rm -rf "$ICONS"
    "$PY" "$KIT/build/icon_theme.py" --out "$ICONS" --inherits "$INHERITS" --anchors "$ANCHORS" | head -1
    command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q -t "$ICONS" || true
    backup "$CFG/com.system76.CosmicTk/v1/icon_theme" "cosmic-tk-icon_theme.ron"
    printf '"remainder"' > "$CFG/com.system76.CosmicTk/v1/icon_theme"
    pgrep -x cosmic-panel >/dev/null 2>&1 && pkill -x cosmic-panel || true   # it reads the icon theme at startup
  else
    say "icons NOT generated — $PY needs Pillow, numpy and cairosvg (set REMAINDER_PYTHON to a venv python)"
    ICONS=''
  fi
else
  ICONS=''
fi

# --- 8. what happened ----------------------------------------------------------------------------
[ "$WANT_FONTS" = 1 ] && [ -z "$FONTS_FAILED" ] && F="fonts ($FONTS)" || F="fonts left alone"
[ -n "$ICONS" ] && [ -d "$ICONS" ] && I="icons ($ICONS)" || I="icons left alone (§4 default)"
if [ "$WANT_ART" = 1 ] && [ -z "$ART_FAILED" ]; then
  B="background: AIC 1938.454 fitted on BLACK (credit in $PICS/CREDIT-aic-1938.454.txt)"
else
  B="background: flat BLACK field (§5 default)"
fi
cat <<MSG
remainder: light mode, theme, toolkit config, terminal scheme; $B; $F; $I.
           what was replaced is in $STATE
Log out/in if the panel, background or terminal does not refresh.
MSG
if [ "$WANT_ART" = 1 ] && [ -z "$ART_FAILED" ]; then cat <<'MSG'
           note: the photograph is shot on a light ground (71.1% of the frame at L 0.74-0.80).
           WHITE over it measures Lc -35.9 at its median against -92.3 on the BLACK field, so the
           desktop's own labels lose the margin §5 buys them. The surround stays BLACK; the middle
           does not. Re-run without --art to go back.
MSG
fi
